#### 1. Preparación del Entorno

In [ ]:
import importlib.util
import sys
import os

# Definir ruta física
path_to_file = os.path.abspath('../src/retail-sales-analysis_P2.py')

# Cargar módulo manualmente
spec = importlib.util.spec_from_file_location("retail_module", path_to_file)
retail_module = importlib.util.module_from_spec(spec)
sys.modules["retail_module"] = retail_module
spec.loader.exec_module(retail_module)

# extraer función
cargar_datos = retail_module.cargar_datos

print("¡Conexión establecida con el archivo .py!")

¡Conexión establecida con el archivo .py!

#### 2. Carga de Datos

In [ ]:
ruta_csv = r'C:\Users\ivanc\Desktop\2. Inversiones\Python_Clases\retail-sales-analysis_P2\data\retail_sales_dataset.csv'
df = cargar_datos(ruta_csv) # Definir Dataframe

print(f'Dataset cargado exitosamente!')
print(f'Dimensiones: {df.shape[0]} filas x {df.shape[1]} columnas')
print(f'Memoria aproximada: {df.memory_usage(deep=True).sum() / 1024:.0f} KB')
print(f'\nColumnas: {list(df.columns)}')

Dataset cargado exitosamente!
Dimensiones: 1000 filas x 9 columnas
Memoria aproximada: 260 KB

Columnas: ['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age', 'Product Category', 'Quantity', 'Price per Unit', 'Total Amount']

* Cargar 10 primeras filas

In [3]:
print("=== 10 primeras filas ===")
print()
print(df.head(10))
print("=========================")

=== 10 primeras filas ===

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty
5               6  2023-04-25     CUST006  Female   45           Beauty
6               7  2023-03-13     CUST007    Male   46         Clothing
7               8  2023-02-22     CUST008    Male   30      Electronics
8               9  2023-12-13     CUST009    Male   63      Electronics
9              10  2023-10-07     CUST010  Female   52         Clothing

   Quantity  Price per Unit  Total Amount
0         3              50           150
1         2             500          1000
2         1              30            30
3         1             500           500
4         2              50           100
5         1              30            30
6         2              25            50
7         4              25           100
8         2             300           600
9         4              50           200
=========================

#### 3. Exploración Inicial de Datos

* 5 primeras filas

In [4]:
print("=== 5 últimas filas ===")
print()
display(df.tail(5))
print("=======================")

=== 5 últimas filas ===

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

=======================

* Información  general

In [32]:
print("=== 5 últimas filas ===")
print()
display(df.info(5))
print("No se encontraron valores nulos.")
print("================================")

=== 5 últimas filas ===

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

None

No se encontraron valores nulos.
================================

* Estadísticas descriptivas

In [27]:
print("=== Estadísticas descriptivas ===")
print()
display(df.describe().round(2))
print("=================================")

=== Estadísticas descriptivas ===

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count         1000.00  1000.00   1000.00         1000.00        1000.0
mean           500.50    41.39      2.51          179.89         456.0
std            288.82    13.68      1.13          189.68         560.0
min              1.00    18.00      1.00           25.00          25.0
25%            250.75    29.00      1.00           30.00          60.0
50%            500.50    42.00      3.00           50.00         135.0
75%            750.25    53.00      4.00          300.00         900.0
max           1000.00    64.00      4.00          500.00        2000.0

=================================

#### 4. Inspección de los Datos

* Tipos de Datos de cada columna

In [7]:
print("=== Tipos de Datos del Dataframe ===")
print()
display(df.dtypes)
print("====================================")

=== Tipos de Datos del Dataframe ===

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

====================================

* Cantidad de valores únicos de la columna 'Product Category'

Nota: El enunciado de la tarea dice: Cuenta los valores únicos en la columna 'Producto' utilizando el método value_counts(). Sin embargo, la columna 'Producto' no existe.

Para seguir con el ejercicio, y habiendo observado las características de cada columna; se decide a usar la columna 'Product Category' para este apartado. Esto ya que los valores de esa columna categórica resultan más interesantes para el análisis posterior, y en un caso real sería necesario y hasta imperativo saber la data de ventas de cada categoría de productos.

In [8]:
print("=== Cantidad de Valores Únicos (Product category)  ===")
print()
display(df['Product Category'].value_counts())
print("======================================================")

=== Cantidad de Valores Únicos (Product category)  ===

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

======================================================

* Valores únicos de la columna 'Product Category'

Nota: El enunciado de la tarea dice: Muestra todos los valores únicos en la columna Tienda utilizando el método unique(). Sin embargo, la columna Tienda no existe.

Para seguir con el ejercicio, y habiendo observado las características de cada columna. Se decide a usar la columna 'Product Category' para este apartado. Esto ya que los valores de esta columna categórica resultan más interesantes para el análisis posterior, y en un caso real sería necesario y hasta imperativo saber las categorías de producto que existen en la firma.

In [28]:
print("=== Tipos de Valores únicos (Product category) ===")
print()
display(df['Product Category'].unique())
print("==================================================")

=== Tipos de Valores únicos (Product category) ===

<StringArray>
['Beauty', 'Clothing', 'Electronics']
Length: 3, dtype: str

==================================================

#### 5. Filtrado de Datos

* Ventas > 50

In [29]:
cond = df['Total Amount'] > 50
print("=== Ventas mayores a 50 ===")
print()
display(df[cond])
print("===========================")

=== Ventas mayores a 50 ===

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
...,...,...,...,...,...,...,...,...,...
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

===========================

* Precio < 0.5

In [33]:
cond = df['Price per Unit'] < 0.5
print("=== Precio menor a 0.5 ===")
print()
display(df[cond])
print("No se encontraron elementos en Precio < 0.5")
print("===========================================")

=== Precio menor a 0.5 ===

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

No se encontraron elementos en Precio < 0.5
===========================================

* Filtrar para: Producto = Manzanas y Ventas > 50

In [34]:
print("=== Producto = 'Clothing' y Ventas > 30 ===")
print()
filtro_query = df.query("`Total Amount` > 30 and `Product Category` == 'Clothing'")
display(filtro_query)
print("===========================================")

=== Producto = 'Clothing' y Ventas > 30 ===

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200
10,11,2023-02-14,CUST011,Male,23,Clothing,2,50,100
...,...,...,...,...,...,...,...,...,...
985,986,2023-01-17,CUST986,Female,49,Clothing,2,500,1000
986,987,2023-04-29,CUST987,Female,30,Clothing,3,300,900
987,988,2023-05-28,CUST988,Female,63,Clothing,3,25,75
990,991,2023-12-26,CUST991,Female,34,Clothing,2,50,100
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50

===========================================

#### 6. Slicing de Datos

* Columnas: Product Category y Ventas

In [25]:
print("=== Columnas: Categoría de Producto y Ventas ===")
print()
display(df[['Product Category', 'Total Amount']])
print("=================================================")

=== Columnas: Categoría de Producto y Ventas ===

    Product Category  Total Amount
0             Beauty           150
1           Clothing          1000
2        Electronics            30
3           Clothing           500
4             Beauty           100
..               ...           ...
995         Clothing            50
996           Beauty            90
997           Beauty           100
998      Electronics           150
999      Electronics           120

[1000 rows x 2 columns]

=================================================

* Filas 5 a 10 y columnas Categoría de Producto y Ventas

In [35]:
print("=== Filas 5 a 10 y columnas Categoría de Producto y Ventas) ===")
print()
seleccion_loc = df.loc[5:10, ['Product Category', 'Total Amount']]
display(seleccion_loc)
print("===============================================================")

=== Filas 5 a 10 y columnas Categoría de Producto y Ventas) ===

   Product Category  Total Amount
5            Beauty            30
6          Clothing            50
7       Electronics           100
8       Electronics           600
9          Clothing           200
10         Clothing           100

===============================================================

* Primeras 5 filas y primeras 3 columnas del DF

In [36]:
print("=== Primeras 5 filas y primeras 3 columnas del DF ===")
print()
seleccion_iloc = df.iloc[0:5, 0:3]
display(seleccion_iloc)
print("=====================================================")

=== Primeras 5 filas y primeras 3 columnas del DF ===

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005

=====================================================